#!/data/data/com.termux/files/usr/bin/sh
name="Tokka"

if [ ! -f "$PREFIX/etc/tconfig/branch" ]; then
	branch="master"
else
	branch=$(cat $PREFIX/etc/tconfig/branch)
fi

if [ ! -f "$PREFIX/etc/tconfig/termux-config.sh" ]; then
	echo "初始化脚本……"
	mkdir -p $PREFIX/etc/tconfig/
	wget -N https://raw.githubusercontent.com/huanruomengyun/$name/$branch/termux-config.sh -P $PREFIX/etc/tconfig/ >/dev/null
fi

if [ ! -f "$PREFIX/etc/tconfig/termux-config.sh" ]; then
	wget -N gh.qingxu.ga/https://raw.githubusercontent.com/huanruomengyun/$name/$branch/termux-config.sh -P $PREFIX/etc/tconfig/ >/dev/null
fi

if [ ! -f "$PREFIX/bin/bash" ]; then
	pkg in bash -y >/dev/null
fi

if [ -f "$PREFIX/etc/tconfig/termux-config.sh" ]
then
	echo "初始化完成…"
else
	echo "请检查您的互联网连接状态，如互联网连接正常，请向开发者提交 issues"
	exit 1
fi

bash $PREFIX/etc/tconfig/termux-config.sh
