#!/data/data/com.termux/files/usr/bin/sh
name="Tiviw"

BLUE=$(printf '\033[34m')

printf "$BLUE"
cat <<-'EOF'
                                                    
_/_/_/_/_/  _/              _/                      
   _/          _/      _/      _/      _/      _/   
  _/      _/  _/      _/  _/  _/      _/      _/    
 _/      _/    _/  _/    _/    _/  _/  _/  _/       
_/      _/      _/      _/      _/      _/          
                                                    
EOF

echo "校验脚本中…"
if [ ! -f "$PREFIX/etc/tiviw/branch" ]; then
	branch="master"
else
	branch=$(cat $PREFIX/etc/tiviw/branch)
fi
if [ ! -d "$PREFIX/etc/tiviw/core" ]; then
	echo "初始化脚本……"
	mkdir -p $PREFIX/etc/tiviw/
	git clone https://github.com/QingxuMo/$name $PREFIX/etc/tiviw/core >/dev/null
fi

if [ ! -d "$PREFIX/etc/tiviw/core" ]; then
	git clone https://github.com.cnpmjs.org/QingxuMo/$name $PREFIX/etc/tiviw/core >/dev/null
fi

if [ ! -f "$PREFIX/etc/tiviw/core/main/menu.sh" ]; then
	echo "请检查您的互联网连接状态，如互联网连接正常，请向开发者提交 issues"
	exit 1
fi

if [ ! -f "$PREFIX/bin/bash" ]; then
	pkg in bash -y >/dev/null
fi

mkdir -p $PREFIX/etc/tiviw/logs
bash $PREFIX/etc/tiviw/core/main/logsmanager.sh
bash $PREFIX/etc/tiviw/core/main/menu.sh | tee -a $PREFIX/etc/tiviw/logs/1.log