#!/data/data/com.termux/files/usr/bin/sh
name="Tovow"
tconfig_ver=0.1

echo "校验脚本中…"
if [ ! -f "$PREFIX/etc/tconfig/branch" ]; then
	branch="master"
else
	branch=$(cat $PREFIX/etc/tconfig/branch)
fi
if [ ! -d "$PREFIX/etc/tconfig/main" ]; then
	echo "初始化脚本……"
	mkdir -p $PREFIX/etc/tconfig/
	git clone https://github.com/QingxuMo/$name $PREFIX/etc/tconfig/main >/dev/null
fi

if [ ! -d "$PREFIX/etc/tconfig/main" ]; then
	git clone https://github.com/QingxuMo/$name $PREFIX/etc/tconfig/main >/dev/null
fi

if [ ! -f "$PREFIX/bin/bash" ]; then
	pkg in bash -y >/dev/null
fi

if [ ! -f "$PREFIX/etc/tconfig/main/script/menu.sh" ]; then
	echo "请检查您的互联网连接状态，如互联网连接正常，请向开发者提交 issues"
	exit 1
fi

bash $PREFIX/etc/tconfig/main/script/menu.sh
